### ISSUE TITLE
Update for 2020

### ISSUE THREAD

**Issue by aslakhol** [dotkom/glowing-fortnight#65]
We need to do the 2020 update, below is a list.

Sjekkliste:
- [ ] Lese igjennom ny på informatikk
- [x] Oppdatere ITEX linken
- [x] Legge inn startdato for fadderukene (kommer i #66)
- [x] Lage og linke til 2020 infoside (lenke kommer i #66)
- [x] Lage fadderuke-events i OW
- [x] Oppdatere API_EVENTS_URL (kommer i #66)
- [x] Lese igjennom ditt liv som Onliner
- [x] Oppdatere komitesøknadsfristen
- [x] Oppdatere sponsorlogoer
- [ ] Coronainfo ?
- [ ] Vurdere om man skal gjøre andre endringer
- [x] Glede seg til fadderuka

**Comment by aslakhol** [comment]
#64 updates itex url

**Comment by aslakhol** [comment]
Øyvind has read through "ditt liv som Onliner"

**Comment by aslakhol** [comment]
#63 makes update application deadline point redundant.
